import style from './style.module.css'
import { useEffect,useState } from "react";
import { useSupabaseClient,useUser } from "@supabase/auth-helpers-react";
import axios from 'axios';

const TeamInvitation = ()=>{

    const [teamInvitations,setTeamInvitations] = useState<any[]>([]);

    const supabaseClient = useSupabaseClient();
    const user = useUser();


    const acceptInvitation = async (invitation_id:number)=>{
            /*
                id bigint generated by default as identity not null,
                created_at timestamp with time zone null default now(),
                status bigint null,
                group_id bigint null,
                admin_user_id uuid null,
                target_user_email text null,
                admin_user_email text null,

                ka_view_user_emails
            */
            // group_members_invitations
            await axios.post('/api/group_members_invitations/accept',{id:invitation_id}).then((d)=>{
                console.log(d);

                alert('ok');
            }).catch((error)=>{
                console.log(error);
                alert('ng');
            });
    }

    useEffect(()=>{
        (async()=>{
            if(user){
                const { data, error } = await supabaseClient
                    .from('ka_group_member_waitinglist')
                    .select()
                    .eq('target_user_email',user.email).eq('status',1);
                    
                if(error){
                    console.log(error);
                }else{
                    setTeamInvitations(data);
                }
            }
        })();
    },[user]);

    return (
        <div className={style.container}>
            {teamInvitations && teamInvitations.length>0? <h2>チームへの招待</h2>: <></>}
            {
                teamInvitations.map((item)=>{
                    return (
                        <div className={style.item} key={item.id} >
                             <div className={style.item_title}>[{item.id}]</div>
                            <div className={style.item_title}>{item.group_id}</div>
                            <div className={style.item_description}>{item.admin_user_email}</div>
                            <div className={style.item_btn} onClick={()=>{acceptInvitation(item.id)}}>Accept</div>
                            <div className={style.item_btn}>Reject</div>
                        </div>
                    );
                })
            }
        </div>
    );
}

export default TeamInvitation;